[package]
name = "three_player_chess"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
rand = "0.8.4"
num-derive = "0.3"
lazy_static = "1.4"
arrayvec = "0.7.2"

[lib]
name = "three_player_chess"

[features]
default = []
debug_movegen = []
